spring.application.name=SpringWebflux-Video-Streaming

spring.data.mongodb.database=media_db
spring.data.mongodb.uri=mongodb://localhost:27017/media_db

# R2DBC Core
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG

# To see Netty I/O
logging.level.io.netty=INFO
spring.codec.max-in-memory-size=200MB
spring.webflux.multipart.max-in-memory-size=500MB
spring.webflux.multipart.max-parts=100

spring.webflux.multipart.enabled=true

